owner: vandreleal
repo: upptime

sites:
  - name: Mapeaks
    url: https://mapeaks-production.herokuapp.com/ping
  - name: Oxidizer
    url: https://oxidizer-rs.github.io
  - name: Runlet
    url: https://runlet.app
  - name: Sentineo
    url: https://sentineo.app

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This page shows the **real-time** status of my personal projects.
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
